### ISSUE TITLE
Very slow to load large quantity of items

### ISSUE THREAD

**Issue by brucedlukens** [CreativeIT/getmdl-select#12]
I am trying to load a large number of items with the select box. What I'm finding is that up to about 15 items it seems to load each menu item quickly (small delay). Above that it gets painfully slow (about 5 seconds to load 100 items, 10 seconds to load 200 items).

**Comment by randrianov** [comment]
hey @brucedlukens, can you send us more details about your issue and we'll try to help you.
email: hello@creativeit.io

**Comment by brucedlukens** [comment]
I sent you an email with more details and some code.

**Comment by randrianov** [comment]
thanks @brucedlukens, have answered you
