### ISSUE TITLE
Performance issue on Safari and IE

### ISSUE THREAD

**Issue by garnold** [CreativeIT/getmdl-select#14]
When a page contains a large number of MDL components, both Safari and IE will lock up for as long as 30 seconds or so.

**Comment by michael-goltsman** [comment]
I faced same issue in IE11 only (Edge worked fine, Safari wasn't tested). The fast and dirty solution I found was to remove 

document.addEventListener("DOMNodeInserted",function(e){
    e.relatedNode.querySelectorAll(".getmdl-select").length>0&&componentHandler.upgradeDom()
},!1)

from the code... I didn't find any problems with removing these lines, but maybe this just irrelevant for my case. Will be thankful to know whether this helped.

**Comment by JeckPikachan** [comment]
Fixed this problem. Thank you for your remarks
