### ISSUE TITLE
Label stays when selecting a value, if the input starts with no value

### ISSUE THREAD

**Issue by fmaylinch** [CreativeIT/getmdl-select#15]
It's related to [this issue](https://github.com/google/material-design-lite/issues/903).

**Comment by randrianov** [comment]
thanks @fmaylinch  will have a look

**Comment by fmaylinch** [comment]
I think you just need to add

`dropdown.classList.add("is-dirty");`

on [line 17](https://github.com/CreativeIT/getmdl-select/blob/master/src/js/getmdl-select.js#L17)

**Comment by fmaylinch** [comment]
Thank you for the component @randrianov

**Comment by fmaylinch** [comment]
I used `classList` but I guess it's better to use `className`.

http://stackoverflow.com/questions/507138/how-do-i-add-a-class-to-a-given-element

**Comment by randrianov** [comment]
@fmaylinch maybe do you want to make a pull-request, ha?

**Comment by fmaylinch** [comment]
Ok, I'll try :)

**Comment by franckevva** [comment]
@fmaylinch Thanks for your work!
