### ISSUE TITLE
Element is invisible because `i.querySelector('.mdl-menu').clientWidth` gets 0

### ISSUE THREAD

**Issue by fmaylinch** [CreativeIT/getmdl-select#19]
In [getmdl-select.js:34](https://github.com/CreativeIT/getmdl-select/blob/master/src/js/getmdl-select.js#L34) I get width 0px so elements are not visible.

If I run `getmdlSelect.init('.getmdl-select');` again I get a correct width but not what I want, because I want the default 300px of `.mdl-textfield` (or whatever I would like to set in my CSS).

I would add an option to enable that line, like a new class `getmdl-select-autowidth`.

Anyway, if you enable that line, it seems that it may get 0px like in my case.

**Comment by franckevva** [comment]
Now you can add a class `getmdl-select__fullwidth ` and field will be stretched to the full width. The default getmdl value is 300px.
