### ISSUE TITLE
Element "is-focused" still after selecting, or even clicking somewhere else

### ISSUE THREAD

**Issue by fmaylinch** [CreativeIT/getmdl-select#20]
For some reason, this line doesn't update the CSS classes well:

    dropdown.MaterialTextfield.change(li.textContent);

It adds `is-dirty` but it doesn't remove `is-focused` so the field appears as focused (with a color underline), even when you click on other places or fields.

I have found this hack. For some reason I have to wait, it doesn't work when called immediately after `change`:

    setTimeout( function() { dropdown.MaterialTextfield.updateClasses_(); }, 250 );

It's quite dirty, and I would prefer to lose focus after clicking somewhere else, but I don't know how to do it.

**Comment by YodaMike** [comment]
thanks @fmaylinch  for the report, we'll see what we can do when there will be free time

**Comment by beaufortfrancois** [comment]
For info, I was able to make it work by doing something like that:

```js
                                                                                                                                            
dropdown.MaterialTextfield.change(li.textContent); // handles css class changes

setTimeout( function() {
  li.parentNode.MaterialMenu.hide();
}, li.parentNode.MaterialMenu.Constant_.CLOSE_TIMEOUT);
                     
```
