### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Ephphatha** [CreativeIT/getmdl-select#22]
The Github repository for this project does not specify a license, however the bower.json file implies that the project is licensed under the MIT License and the package.json file implies that the project is licensed under the ISC License. There's no explicit license statement or list of copyright holders apart from what can be inferred in the contributors list.

It would be useful if you could include a license file to clarify permitted use.

**Comment by randrianov** [comment]
@Ephphatha Thanks! It's MIT, will add it to readme.
