### ISSUE TITLE
support multi-select

### ISSUE THREAD

**Issue by haoxins** [CreativeIT/getmdl-select#26]
Such as

![wechat_1467012616](https://cloud.githubusercontent.com/assets/8917336/16371911/1093fd0e-3c7c-11e6-97e9-3321f8bf2526.jpeg)

**Comment by randrianov** [comment]
@haoxins thanks for a interesting thought. Maybe you able to work on pull-request of this feature, ha?
For now I only found angular-material here https://material.angularjs.org/latest/api/directive/mdSelect with 'multiple' param.
Anyway will do extra research and if all will look fine add this feature in the next milestone.

**Comment by salimane** [comment]
any update on this ?

**Comment by acollazomayer** [comment]
Any update?
