### ISSUE TITLE
Issue in scrolable dropdown

### ISSUE THREAD

**Issue by raza-ahmed** [CreativeIT/getmdl-select#29]
If the values in the list is more, then the elements are not scrollable it takes the whole page and also increases the page height of html document. I have attached the screenshot of the issue.

<img width="365" alt="screen shot 2016-08-22 at 3 27 13 pm" src="https://cloud.githubusercontent.com/assets/1610591/17850910/fec7cc54-687c-11e6-8d1b-dad13cd3603c.png">

**Comment by franckevva** [comment]
look pull request #30
If you want to use small height (300px) and see scroll bar, add class `getmdl-select__fix-height`.
