### ISSUE TITLE
firefox

### ISSUE THREAD

**Issue by edparsons** [CreativeIT/getmdl-select#31]
Hi there, for firefox the input box gets focused and the menu is never opened. Is this problem common to other people or have I set the component up wrong?

**Comment by franckevva** [comment]
@edparsons 
Interesting.
Tested it in firefox. Menu is open normal, but doesn't lose focus. Will fix focus problem soon

**Comment by JeckPikachan** [comment]
Tested it too. Works properly. @edparsons maybe you forgot to use "init" function?
