### ISSUE TITLE
Items should appear over the emitting element.

### ISSUE THREAD

**Issue by AykutCevik** [CreativeIT/getmdl-select#32]
As mentioned in [Google Material](https://material.google.com/components/menus.html#menus-behavior), the menu should appear over the element.

**Comment by JeckPikachan** [comment]
This issue appears because of property "overflow: hidden", which some blocks and elements have. You can solve it, for example adding this code:

`.mdl-card, .mdl-card__supporting-text {
    overflow: inherit;
}`
