### ISSUE TITLE
.getmdl-select__fullwidth slightly off

### ISSUE THREAD

**Issue by jefferythewind** [CreativeIT/getmdl-select#35]
I have this definition for the Gender input: 

`<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">`

<img width="300" alt="screen shot 2016-09-07 at 11 05 19" src="https://cloud.githubusercontent.com/assets/18137743/18306205/00120334-74eb-11e6-99f6-f9bce88dbbe7.png">

You can see the input is slightly less than what I have for the general textfield width.  I noticed that a `style="XXXpx;` attribute is added directly to the element.  When I turn this off in the browser, the input reverts to the correct width: 

<img width="482" alt="screen shot 2016-09-07 at 11 08 18" src="https://cloud.githubusercontent.com/assets/18137743/18306286/6a361688-74eb-11e6-82e5-41c490f1c8c9.png">

What I am thinking is, at the bottom of the JS script, this function sets the width:

```
       init: function (selector, widthDef) {
            var dropdowns = document.querySelectorAll(selector);
            [].forEach.call(dropdowns, function (i) {
                getmdlSelect.addEventListeners(i);
                var width = widthDef ? widthDef : (i.querySelector('.mdl-menu').offsetWidth ? i.querySelector('.mdl-menu').offsetWidth : getmdlSelect.defaultValue.width);
                i.style.width = width + 'px';
            });
        }
```

Instead of explicitly setting the width every time, only set the width when users haven't added the `getmdl-select__fullwidth` class?  So since I have added the class, the JS won't alter the width of my input.

Nice work.

**Comment by Fireztonez** [comment]
I have the same isue and I need to fix it. No body reply here for any problem??

**Comment by jefferythewind** [comment]
I ended going a different direction with my form.  It uses the default `<select>` element with MDL styling.  I think the result is pretty nice.

```
<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label {% if form.errors.gender %}is-invalid{% endif %}">
	<label class="mdl-textfield__label" for="gender">Gender</label>
	<select class="mdl-textfield__input" id="id_gender" name="gender">
		<option value=""></option>
		<option value="Male">Male</option>
		<option value="Female">Female</option>
		<option value="Transgender">Transgender</option>
		<option value="Other">Other</option>
	</select>
	<span class="mdl-textfield__error">{{ form.errors.gender.as_text }}</span>
</div>
```

Actually works pretty nice.

**Comment by alexbananabob** [comment]
Hi, guys! I resovle this bug in **"fix bug for class .getmdl-select__fullwidth. #issue #35"**. Now class **.getmdl-select__fullwidth** working correctly and getmdl-select takes 100% of width his parent. Also initial width for getmdl-select is 300px. You can change it by adding CSS rule for class **.getmdl-select**. For example, like:
```
.getmdl-select {
    width: 200px;
}
```
Thanks
