### ISSUE TITLE
name in input

### ISSUE THREAD

**Issue by afabros** [CreativeIT/getmdl-select#39]
this is just a suggestion: <input class="mdl-textfield__input" type="text" id="sample1" value="Belarus" readonly tabIndex="-1"> Thank you for this code that allowed me to go on with MDL. Kindly add name="sample1" in the document to avoid confusion when the input is not giving back the value from the server upon submission of the form. Thank you again.

**Comment by alexbananabob** [comment]
@afabros Thank you for your comment. Issue is resolved.
