### ISSUE TITLE
getmdl-select with a textfield in one line?

### ISSUE THREAD

**Issue by sc30** [CreativeIT/getmdl-select#42]
I would like to do add getmdl-select with a textfield in one line, something like this:

![The way that I wanted](https://camo.githubusercontent.com/4f2ea8a34177e5ef6644514e50f179c9bac456be/68747470733a2f2f6d6174657269616c2d64657369676e2e73746f726167652e676f6f676c65617069732e636f6d2f7075626c6973682f6d6174657269616c5f765f342f6d6174657269616c5f6578745f7075626c6973682f30425f75644f354238707a727a4d31394b596b524a616b70714e56452f636f6d706f6e656e74735f6d656e75735f6265686176696f72322e706e67)

The textfield New York, getmdl-select NY and textfield Postcode in one line.

Sorry I am new to this, so any help would be appreciated. Thanks

**Comment by sc30** [comment]
I could change width to 50% from class .mdl-textfield__input, but the drop down effect still display the normal width

**Comment by JeckPikachan** [comment]
There is no problem to do this. You just put your elements one by one. Like this for instance:
![image](https://user-images.githubusercontent.com/3951464/28018276-5586d49e-6585-11e7-814b-daee76f33e6d.png)

**Comment by JeckPikachan** [comment]
> I could change width to 50% from class .mdl-textfield__input, but the drop down effect still display the normal width

It's better to change width of containing div (.mdl-textfield or .getmdl-select)
