### ISSUE TITLE
componentHandler.upgradeDom() on DOMNodeInserted causes "call stack size exceeded" error

### ISSUE THREAD

**Issue by ntoljic** [CreativeIT/getmdl-select#44]
I ran into this issue while working on a CRM with a rather complex UI.

The `DOMNodeInserted` listener that gets added in `window.onload` calls `componentHandler.upgradeDom()` to ensure that dynamically added select boxes are upgraded properly. This has the side effect of upgrading the entire DOM every time any Node is inserted. This, in turn, causes (in my tests in Chrome) to return a bunch of `Uncaught RangeError: Maximum call stack size exceeded` errors.

I would suggest to:
  - implement a targeted upgrade of the element being added
  - perfoming the upgrade logic after ensuring that the newly inserted node is a potential candidate

I solved the issue in the meantime by simply removing the call to `upgradeDom()` and manually calling `getmdlSelect.init('.getmdl-select');` where appropriate.

**Comment by JeckPikachan** [comment]
Thank you for suggestion. We fixed it.
