### ISSUE TITLE
It does not work when the element is called via JavaScript

### ISSUE THREAD

**Issue by darwindlrd** [CreativeIT/getmdl-select#49]
![captura de pantalla 100](https://cloud.githubusercontent.com/assets/20263111/23346398/85ba7966-fc5f-11e6-98b7-c7a919b57013.png)
When you click on a button to load the form through JavaSccript stops working.

What does it mean? Well, changing "country" does not accept it, ie it is fixed in Germany

HTML:

`<div class="mdl-card__actions mdl-card--border">
								<a onclick="myFunction()" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">Get Started</a>
							</div>`

`<section  class="maia-aux">
					<div id="business"></div>
				</section>`

The content loads in the "business"

And JavaScript

`function myFunction() {
	registrationSection.classList.add('hide');
    var business = document.getElementById('business');
    business.innerHTML = 
    `<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fullwidth">
            <input class="mdl-textfield__input" type="text" id="sample1" value="Belarus" readonly tabIndex="-1">
            <label for="sample1" class="mdl-textfield__label">Country</label>
            <ul for="sample1" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                <li class="mdl-menu__item">Germany</li>
                <li class="mdl-menu__item">Belarus</li>
                <li class="mdl-menu__item">Russia</li>
            </ul>
        </div>
    componentHandler.upgradeElements(business);
};`

**Comment by JeckPikachan** [comment]
@darwindlrd  have you called "getmdlSelect.init(cssSelector)" function?
