### ISSUE TITLE
How to handle events on select

### ISSUE THREAD

**Issue by javierdelpozo** [CreativeIT/getmdl-select#50]
Hi!

Im using it with the rest of mdl, and i would like to know how to hanlde the select event, or if i should have to use the text input event instead? im a bit lost with the mdl event handlers.

thanks,

**Comment by franckevva** [comment]
Hi, @javierdelpozo 
You should have to use [change](https://www.w3schools.com/jsref/event_onchange.asp ) event of the text input. Not special mdl events.
Example

         var input = document.querySelector('.mdl-textfield__input');
         input.onchange = function ($e) {
            console.log('change', $e);
           // your code
        };
