### ISSUE TITLE
selected item from drowdown list  is not set

### ISSUE THREAD

**Issue by shwetarc** [CreativeIT/getmdl-select#53]
Dynamic data is displayed in drop down list but when we try to select item from drop down nothing is happened, selected item not set to the label

**Comment by micleb** [comment]
Hi I have the same issue

**Comment by xilaworp** [comment]
Had the same issue but the reason was I had forgotten to include the getmdl-select js and css (see docs).

**Comment by dverdere** [comment]
I am having the same problem on one of the selects, but not the other. very confused by the issue and not sure how to start debugging

**Comment by pedropilla** [comment]
I'm having the same problem too, apparently my form is receiving the <li> value, not the "value" or "data-val" attr. My solution to this was change the function name to match the label, but that's not reasonable at all.

**Comment by JeckPikachan** [comment]
@shwetarc  @dverdere @micleb  Can't find a way to do it wrong. Can you give an example of your code? Haven't you forgotten to include the getmdl-select js and css  as @xilaworp does?

**Comment by JeckPikachan** [comment]
@shwetarc @dverdere @micleb Also, issue can be that you forgot to call "getmdlSelect.init(cssSelector)" function.

**Comment by dverdere** [comment]
@JeckPikachan this ultimately ended up being my issue. Did not see this in the README until after
