### ISSUE TITLE
Issue with overflow

### ISSUE THREAD

**Issue by micleb** [CreativeIT/getmdl-select#54]
Hi, I have an issue with the getmdl-select and its parent container.
The select doesn't display if the container is too small : https://i.imgur.com/Jrns1YI.png
The select's elements should appear in the blue square but they are hidden behind the mdl-card.

How to prevent this behavior ?

Thanks

**Comment by ar-post** [comment]
```
.mdl-card, .mdl-card__supporting-text {
    overflow: inherit;
}
```
[from](https://github.com/google/material-design-lite/issues/943#issuecomment-270160273)
