### ISSUE TITLE
client site's onload call back getting knocked off

### ISSUE THREAD

**Issue by tapsey** [CreativeIT/getmdl-select#56]
Implementing websites' onload callback not called. Issue is caused by :

`  window.onload = function () {
        getmdlSelect.init('.getmdl-select');
        document.addEventListener("DOMNodeInserted", function (ev) {
            if (ev.relatedNode.querySelectorAll(".getmdl-select").length > 0) {
                componentHandler.upgradeDom();
            }
        }, false);
    };`

You can use 

`window.addEventListener ? 
    window.addEventListener("load",mWhenLoaded,false) : 
    window.attachEvent && window.attachEvent("onload",mWhenLoaded);
`

    function mWhenLoaded() {
        getmdlSelect.init('.getmdl-select');
        document.addEventListener("DOMNodeInserted", function (ev) {
            if (ev.relatedNode.querySelectorAll(".getmdl-select").length > 0) {
                componentHandler.upgradeDom();
            }
        }, false);
    };`

**Comment by JeckPikachan** [comment]
Thank you for this issue. Merged your pull request.
