### ISSUE TITLE
Menu not triggered when page is rebuilt

### ISSUE THREAD

**Issue by dafooz** [CreativeIT/getmdl-select#6]
Hi, in my app, the container and the input are automatically rebuilt after selecting a value in the drop down menu. My problem is that any click on the input field won't show the menu anymore. It looks like the reference is lost... Any idea how to re initialise the mennu or force it to show on click on the input?

Thanks!

Great job by the way... Keep it up

**Comment by randrianov** [comment]
@dafooz thanks for report, will have a look and suggest the best way.

**Comment by dafooz** [comment]
Thanks a lot, I'm looking at how to do it on my side as well. If I find
something I'll let you know!

**Comment by dafooz** [comment]
Hi, you can disregard this comment, I managed to have it work by calling "componentHandler.upgradeDom();" on the page rebuild.

**Comment by franckevva** [comment]
@dafooz greate work!

**Comment by dafooz** [comment]
Thanks! Keep up the good work!
