### ISSUE TITLE
Select doesn't close with some interactions.

### ISSUE THREAD

**Issue by Werewolfkiss** [CreativeIT/getmdl-select#65]
There's 3 interactions we noticed that don't close the menu which we would expect to close the menu.

1. Pressing Tab on the keyboard to move to a next field. 
          This could be fixed by updating the key listener to also listen for tabs and close the menu.
2. Pressing the Down arrow on an iPhone Previous/Next/Done bar. It moves the focus to the next input field just like Tab would, but the menu doesn't close. 
3. Pressing the arrow on the input field after opening the menu

**Comment by alexbananabob** [comment]
Thanks, Werewolfkiss 
Will fix this in a new release
