### ISSUE TITLE
Box-shadow on menu missing

### ISSUE THREAD

**Issue by nathanjosiah** [CreativeIT/getmdl-select#66]
The `overflow: hidden` on `.getmdl-select .mdl-menu__container` and the `overflow-y: auto` on `.getmdl-select__fix-height .mdl-menu__container` is causing the shadow of the menu to be lost. This can be seen on both of the demo configurations. 

Partially (sometimes fully) missing on:
![image](https://user-images.githubusercontent.com/665104/32119974-c796eab6-bb0b-11e7-8e2b-ea6789071e98.png)

and totally missing on:
![image](https://user-images.githubusercontent.com/665104/32119934-9dfd1ef0-bb0b-11e7-9575-651d98d408cd.png)

compare to the [mdl menu](https://getmdl.io/components/index.html#menus-section):
![image](https://user-images.githubusercontent.com/665104/32119950-abfef87a-bb0b-11e7-88ff-a3337508a5f1.png)

**Comment by alexbananabob** [comment]
Thanks, Nathanjosiah
Will fix this in a new release
