### ISSUE TITLE
Items is not selected

### ISSUE THREAD

**Issue by github-polymer-user** [CreativeIT/getmdl-select#7]
select is not working tried this:

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select">
            <input class="mdl-textfield__input" type="text" id="sample2" value="Belarus" readonly tabIndex="-1">
            <label for="sample2">
                <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
            </label>
            <label for="sample2" class="mdl-textfield__label">Country</label>
            <ul for="sample2" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                <li class="mdl-menu__item">Germany</li>
                <li class="mdl-menu__item">Belarus</li>
                <li class="mdl-menu__item">Russia</li>
            </ul>
        </div>

**Comment by randrianov** [comment]
@github-polymer-user did you include scripts from this section https://github.com/CreativeIT/getmdl-select#basic-use ?
Thank you for question

**Comment by github-polymer-user** [comment]
@randrianov I suppose that error comes from the fact that I created ddl lists dynamically, with Polymer importHref, and your control spports static controls only.
