### ISSUE TITLE
getmdl-select isn't working with AngularJS ng-repeat list (Dynamic list)

### ISSUE THREAD

**Issue by AmitBenAmi** [CreativeIT/getmdl-select#73]
I'm working now with AngularJS 1.6 and set the li with ng-repeat. The component works but when selecting a value the field (input) not showing what value I selected, and also the ng-model which I've bound isn't getting the real selected value.
After some debugging and seeing what your code does, I figured out what should be done.
Knowing when AngularJS finishes rendering the ng-repeat list, I called **getmdlSelect.init(.getmdl-select)**, which solved my problem, because on load the foreach loop in the getmdlSelect can't find any li elements (Angular still didn't rendered it yet), thus the _addEventListeners that called in the getmdlSelect.init finds empty list of li elements.
When knowing when AngularJS finished rendering and re-calling the getmdlSelect.init function with the .getmdl-select class, now the _addEventListeners can find all of the rendered AngularJS dynamic list of li.
That solved my problem and maybe should be noted on your site

**Comment by alexbananabob** [comment]
Thanks you @AmitBenAmi for you feedback.
However, we wrote about it in [Dynamically usage](https://github.com/CreativeIT/getmdl-select#dynamically-usage) section

**Comment by AmitBenAmi** [comment]
Hi @alexbananabob,
You’re right, didn’t noticed that
Thank you!


Sent from Mail for Windows 10
