### ISSUE TITLE
getmdl-select__fix-height does not add scrollbar in chrome

### ISSUE THREAD

**Issue by kevinsamoei** [CreativeIT/getmdl-select#76]
According to the docs, by adding `getmdl-select__fix-height` class it should add an height of `300px` and one can view a scrollbar. This works very well in other browsers except for Google chrome.

**Comment by alexbananabob** [comment]
Hi, @kevinsamoei 
Works well in Google Chrome for me. 
Check, please, maybe you did something wrong
