### ISSUE TITLE
Select not working

### ISSUE THREAD

**Issue by rjshreve** [CreativeIT/getmdl-select#8]
Hi,

I have many of these fields is my program I'm building. It's a dynamic form that allows for dynamically added and removing rows. The first row that appears on page load works fine. The rest of them, which are added by DOM are added and get upgraded it seems but when the dropdown appears and I click on a value, the doesn't actually select the value. The dropdown goes away and the field remains blank. Any help would be great! Thank you!

**Comment by franckevva** [comment]
@rjshreve Hi!
For quick fix you can add function addEventListeners from https://github.com/CreativeIT/getmdl-select/blob/master/src/js/getmdl-select.js to you project for initialize new components by yourself. Then we will add publish function for it and notify you.

**Comment by rjshreve** [comment]
I was not able to get this working...I will have to wait for fix.

Thank you!

**Comment by franckevva** [comment]
@rjshreve Hey!
You can update getmdl-select and try now!  
For dynamically usage, you must add getmdlSelect.init(container) in javascript code, where container is div block (for example <div class='getmdl-select'></div>), after new item is created

**Comment by franckevva** [comment]
@rjshreve Hey!
You can update getmdl-select and try now!
For dynamically usage, you must add `getmdlSelect.init(cssSelector)` in javascript code, (where cssSelector, for example, is `".getmdl-select"` or `"#mySelect"`), after new item is created.
