### ISSUE TITLE
Dynamically add select

### ISSUE THREAD

**Issue by OhhConti** [CreativeIT/getmdl-select#80]
I'm trying to use your select component, but I'm not able to add it dynamically, here is the code
[dyanmicallyselect.txt](https://github.com/CreativeIT/getmdl-select/files/2013716/dyanmicallyselect.txt)

**Comment by femarschall** [comment]
Your aproach is a bit messy and I don't know why the last node "Slider" is inside an "AP" element and not inside a "li" element as the previous others..

And you are not using the init function as stated in the instructions:
Dynamically usage
For dynamically usage, you must add getmdlSelect.init(cssSelector)

**Comment by femarschall** [comment]
I made it work adding the following line after "componentHandler.upgradeDom();" :

getmdlSelect.init('#contenitore .getmdl-select:last-child');

**Comment by alexbananabob** [comment]
@femarschall, many thanks for your answer. It is right.
@OhhConti, Hope @femarschall's answer helped you.
