### ISSUE TITLE
Padding Modification Misaligns Animation

### ISSUE THREAD

**Issue by korndog** [CreativeIT/getmdl-select#82]
If I modify the the top and bottom padding of an MDL select field then the label and animation are subsequently misaligned. For example:

<div class="mdl-textfield mdl-js-textfield getmdl-select" style="padding-bottom:4px; padding-top:4px;">

Per https://stackoverflow.com/questions/42739168/reduce-or-remove-vertical-padding-of-mdl-textfields, the label can be fixed by modifying the "top" style of "mdl-textfield__label". However, modifying the "bottom" style of "mdl-textfield__label:after" does not fix the animation. The animation is still too high. Is there a way to fix the animation? Thank you!

**Comment by alexbananabob** [comment]
Hi, @korndog 
Not sure that understood you problem. And can't reproduce it. Provide, please, some examples of code or images
