### ISSUE TITLE
[Proposal] Search input

### ISSUE THREAD

**Issue by lloydbanks** [CreativeIT/getmdl-select#84]
You made a really nice component that everyone needs in MDL.

But I have only one suggestion, please include a search input. e.g: for countries/cities/rubrics it'd be much easier to type the first letters and find the desired item quickly instead of scrolling a long list. 

[Demo](https://phppot.com/demo/dropdown-with-search-using-jquery/)

I believe it would be a nice feature. Thanks.

**Comment by alexbananabob** [comment]
Hi, @lloydbanks 
Thank you for your feedback. 
It is realy nice feature
I think we will implement it in new releases
Many thanks!
