### ISSUE TITLE
Hidden input does not work with Angular JS

### ISSUE THREAD

**Issue by NihalAG** [CreativeIT/getmdl-select#85]
Hidden field implementation doesn't work with 2 way binding on Angular JS
Link for reference:
https://github.com/angular/angular.js/pull/2574

**Comment by alexbananabob** [comment]
Hi @NihalAG,
`getmdl-select` was created for VanillaJS like "native" select with material design. And don't have integration with any frameworks. Integration with a framework is the task of the developer who uses this framework. 
Thanks
