### ISSUE TITLE
MDL Select Doesn't work nicely with HTML tags / Material Icons

### ISSUE THREAD

**Issue by dfsoeten** [CreativeIT/getmdl-select#86]
So, my issue is the following: I'm trying to make the select work with HTML / Material Icons like so: 

```
<li class="mdl-menu__item" data-val="red-500" tabindex="-1">
    <i class="material-icons mdl-color-text--red-500">fiber_manual_record</i>Red
</li>
```

Wich has the following result: 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/19746471/41818041-1fa8cec4-77a7-11e8-819c-d51ed556379f.png">

But when I select that item it doesn't parse(?) the HTML / Material Icon properly: 

<img width="313" alt="image" src="https://user-images.githubusercontent.com/19746471/41818045-3b396298-77a7-11e8-998a-761b79ac9f1f.png">

Any ideas how I can get this to work? 😉

**Comment by alexbananabob** [comment]
Hi @iamdann,
Sorry, but now `getmdl-select` only supports text values for options. 
But it is good idea to add custom HTML support.
Thank you

**Comment by dfsoeten** [comment]
Thanks for the update!
