### ISSUE TITLE
JS onSelect Function

### ISSUE THREAD

**Issue by charanjit-singh** [CreativeIT/getmdl-select#88]
Hello Sorry to raise this issue, without reading the docs,
 but can anyone please tell me how to implement onSelect listener in mdl??

**Comment by alexbananabob** [comment]
Hi @charanjit-singh,
Do you mean this event type https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onselect#Notes ?

**Comment by charanjit-singh** [comment]
No @alexbananabob 
Which event gets fired when we select a dropdown item??

**Comment by alexbananabob** [comment]
The event name is `change`. You should listen and add handler for `.mdl-textfield__input`, because this event don't bubble
