### ISSUE TITLE
dynamically usage

### ISSUE THREAD

**Issue by randrianov** [CreativeIT/getmdl-select#9]
#8 Provide public object with method init
mdlSelect.init(cssSelector)
or try to subscribe on native mdl event http://www.getmdl.io/started/index.html#dynamic

**Comment by franckevva** [comment]
For dynamically usage, add getmdlSelect.init(cssSelector) in javascript code, (where cssSelector, for example, is ".getmdl-select" or "#mySelect"), after new item is created.

**Comment by randrianov** [comment]
@franckevva please add new section ('dynamically usage') to common description with code samle, thanks
