### ISSUE TITLE
Fixed height

### ISSUE THREAD

**Issue by OhhConti** [CreativeIT/getmdl-select#90]
I was using mdl-select in my project.
I wonder if there is a way to **change** the **height** value of the class "**getmdl-select__fix-heigh**t".
That is set to 300px by default.

**Comment by alexbananabob** [comment]
Hi, @OhhConti 
Override `max-height` property with `!important` using `.getmdl-select__fix-height .mdl-menu__container .mdl-menu` selector in your stylesheet for this.
