### ISSUE TITLE
data-selected "true" is setting wrong selected tag

### ISSUE THREAD

**Issue by lynnpark** [CreativeIT/getmdl-select#93]
When I set data-selected to true on a dropdown list item, the wrong list item gets selected, as shown here:

![image](https://user-images.githubusercontent.com/9057509/49029873-c85ef700-f173-11e8-8f66-79f1cfcf6395.png)

**Comment by jkaan** [comment]
@lynnpark Hi! I ran into this problem myself as well and I think this PR fixes it: #95. You can add this change to your own code already to make it work.

**Comment by lynnpark** [comment]
> @lynnpark Hi! I ran into this problem myself as well and I think this PR fixes it: #95. You can add this change to your own code already to make it work.

This worked! Thank you so much!
