### ISSUE TITLE
Problem with setting dinamic value to mdl select

### ISSUE THREAD

**Issue by vmellos** [CreativeIT/getmdl-select#98]
When the page loads I need to set a value from JSON to this select

                <div class="mdl-textfield mdl-js-textfield getmdl-select mdl-textfield--floating-label">
                      <input type="text" value="" class="mdl-textfield__input" id="letter" readonly>
                      <input type="hidden" value="" name="letter">
                      <label for="letter" class="mdl-textfield__label">Choose</label>
                      <ul for="letter" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                        <li class="mdl-menu__item" data-val="1">A</li>
                        <li class="mdl-menu__item" data-val="2">B</li>
                        <li class="mdl-menu__item" data-val="3">C</li>
                        <li class="mdl-menu__item" data-val="4">D</li>
                        <li class="mdl-menu__item" data-val="5">E</li>
                      </ul>
                    </div>
`

**Comment by nomanalikhan** [comment]
Hey, I'm having the same problem, The value got reset when clicking outside the field  Any luck with this issue?
